# Site settings
title: ZeTiXaR
header-img: img/home-bg.png
email: mohsendp@gmail.com
copyright_name: zetixar
description: > # this means to ignore newlines until "baseurl:"
  Strategic Creativity and Gamification
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  zetixar
learn_profile: zetixar
email_username: mohsendp@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
